name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.2]
        node-version: [18.x]


    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install wkhtmltopdf
        run: |
              sudo apt-get update
              sudo apt-get install -y wkhtmltopdf
              
      - name: Does it work
        run: which wkhtmltopdf
        continue-on-error: true
